name: Example workflow using Snyk
on:
  - push
  - pull_request
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor # Default command is `test`
          args: |
            --all-projects
            --fail-fast
# other args:
            # --reachability=<true|false>
            # --exclude=<NAME>[,<NAME>]...>
            # --prune-repeated-subdependencies
            # --project-name=<PROJECT_NAME>
            # --ignore-policy